version: '3.1'
services:
    cupsserver:
        image: cupsserver
        restart: unless-stopped
        volumes:
            - ./data:/data
        ports:
            - 631:631
            - 8181:80
        environment:
          TZ: Asia/Vladivostok
          CUPS_ADMIN_PASSWD: 12345678
          APP_DOMAIN: cups.domain.tld